export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const SIGNUP_EMAIL = "SIGNUP_EMAIL";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAIL = "SIGNUP_FAIL";
export const PROFILE_PICK_SUCCESS = "PROFILE_PICK_SUCCESS";
export const PROFILE_CHANGE_SUCCESS = "PROFILE_CHANGE_SUCCESS";
